### ISSUE TITLE
LFS has broken merge

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#219]
LFS was installed to host files 100M+

merge task is now broken
```
1s
38s
12s
0s
0s
Run ad-m/github-push-action@master
Push to branch master
error: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/rusefi/rusefi.wiki.git'
Error: Invalid exit code: [1](https://github.com/rusefi/rusefi_documentation/runs/7034679439?check_suite_focus=true#step:5:1)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:2[8](https://github.com/rusefi/rusefi_documentation/runs/7034679439?check_suite_focus=true#step:5:9)7:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:2[9](https://github.com/rusefi/rusefi_documentation/runs/7034679439?check_suite_focus=true#step:5:10):21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:[10](https://github.com/rusefi/rusefi_documentation/runs/7034679439?check_suite_focus=true#step:5:11)22:[16](https://github.com/rusefi/rusefi_documentation/runs/7034679439?check_suite_focus=true#step:5:17))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by rusefillc** [comment]
https://github.com/git-lfs/git-lfs/issues/2291 seems to be relevant

**Comment by rusefillc** [comment]
@chuckwagoncomputing i have fresh painpoint which makes very little sense

**Comment by rusefillc** [comment]
```
rm .git/hooks/pre-push
```
helps locally - as described at https://github.com/git-lfs/git-lfs/issues/2291#issuecomment-305874747

**Comment by rusefillc** [comment]
wow that weird hack has helped

**Comment by chuckwagoncomputing** [comment]
If I understand correctly, removing the hook means that LFS will not be used.

**Comment by rusefillc** [comment]
we might not even have any links to .pdf files in the affected folders

worst case we will have full URL of documentation wiki
